-- ------------------------------------------------------------------------------------------------
-- ---------- 创建材料 ----------------------------------------------------------------------------
-- ------------------------------------------------------------------------------------------------

SIGen.NewTypeRecipe( SIEXHS.recipeType )
.NewSubGroup( "hyperspace-base" )
.NewSubGroup( "hyperspace-structure" )
.NewSubGroup( "hyperspace-electricity" )
.NewSubGroup( "hyperspace-others" )

SIEXHS.coreItem = SIGen.NewItem( "main-core" ).GetCurrentEntityName()
SIEXHS.autoItem = SIGen.NewItem( "main-core-automation" ).GetCurrentEntityName()
SIEXHS.wallItem = SIGen.NewItem( "super-wall" , 25 ).GetCurrentEntityName()
SIEXHS.gel3Item = SIGen.NewItem( "gel-3" , 45 ).GetCurrentEntityName()
SIEXHS.gel7Item = SIGen.NewItem( "gel-7" , 45 ).GetCurrentEntityName()
SIEXHS.lightItem = SIGen.NewItem( "light" , 10 ).GetCurrentEntityName()

-- ------------------------------------------------------------------------------------------------
-- ---------- 创建配方 ----------------------------------------------------------------------------
-- ------------------------------------------------------------------------------------------------

SIGen

.NewRecipe( SIEXHS.coreItem )
.SetEnergy( 30 )
.SetEnabled( true )
.AddCosts( "stone" , 15 )
.AddCosts( "iron-ore" )
.AddCosts( "copper-ore" )
.AddResults( SIPackers.SingleItemProduct( "stone" , 0.65 , 2 , 3 , 3 ) )
.AddResults( SIPackers.SingleItemProduct( SIEXHS.coreItem , 0.002 , 1 , 1 , 1 ) )
.SetSelfIcon( "main-core" )

.NewRecipe( SIEXHS.autoItem )
.SetEnergy( 70 )
.SetEnabled( true )
.AddCosts( "iron-plate" , 15 )
.AddCosts( "iron-stick" , 25 )
.AddCosts( "iron-gear-wheel" , 12 )
.AddCosts( "copper-plate" , 5 )
.AddCosts( SIEXHS.coreItem )
.AddResults( SIPackers.SingleItemProduct( SIEXHS.autoItem , 1 , nil , nil , 1 ) )

.NewRecipe( SIEXHS.coreItem.."-2" )
.SetEnergy( 90 )
.SetEnabled( true )
.SetRecipeTypes( SIEXHS.recipeType )
.AddCosts( "stone" , 8 )
.AddCosts( "wood" , 35 )
.AddCosts( "raw-fish" , 6 )
.AddCosts( SIEXHS.coreItem )
.AddResults( SIPackers.SingleItemProduct( "stone" , 0.65 , 2 , 3 , 3 ) )
.AddResults( SIPackers.SingleItemProduct( SIEXHS.coreItem , 0.01 , 1 , 1 , 1 ) )
.AddResults( SIPackers.SingleItemProduct( SIEXHS.coreItem , 1 , nil , nil , 1 ) )
.SetSelfIcon( "main-core-2" )

.NewRecipe( SIEXHS.gel3Item )
.SetEnergy( 9 )
.SetEnabled( true )
.SetRecipeTypes( SIEXHS.recipeType )
.AddCosts( "iron-plate" )
.AddCosts( SIPackers.SingleFluidIngredient( "steam" , 25 , 150 , 220 ) )
.AddCosts( SIEXHS.coreItem )
.AddResults( SIEXHS.gel3Item )
.AddResults( SIPackers.SingleItemProduct( SIEXHS.coreItem , 1 , nil , nil , 1 ) )
.SetSelfIcon( "gel-3" )

.NewRecipe( SIEXHS.gel7Item )
.SetEnergy( 45 )
.SetEnabled( true )
.SetRecipeTypes( SIEXHS.recipeType )
.AddCosts( "coal" , 32 )
.AddCosts( "copper-ore" , 25 )
.AddCosts( SIEXHS.gel3Item , 15 )
.AddCosts( SIEXHS.coreItem )
.AddResults( SIEXHS.gel7Item , 5 )
.AddResults( SIPackers.SingleItemProduct( SIEXHS.coreItem , 1 , nil , nil , 1 ) )
.SetSelfIcon( "gel-7" )

.NewRecipe( SIEXHS.wallItem )
.SetEnergy( 45 )
.SetEnabled( true )
.SetRecipeTypes( SIEXHS.recipeType )
.AddCosts( "automation-science-pack" , 4 )
.AddCosts( "stone-wall" , 15 )
.AddCosts( "steel-plate" , 25 )
.AddCosts( SIEXHS.coreItem )
.AddResults( SIEXHS.wallItem , 2 )
.AddResults( SIPackers.SingleItemProduct( SIEXHS.coreItem , 1 , nil , nil , 1 ) )
.SetSelfIcon( "super-wall" )

.NewRecipe( SIEXHS.lightItem )
.SetEnergy( 110 )
.SetEnabled( true )
.SetRecipeTypes( SIEXHS.recipeType )
.AddCosts( "wood" , 4 )
.AddCosts( SIEXHS.wallItem , 10 )
.AddCosts( SIEXHS.gel3Item , 5 )
.AddCosts( SIEXHS.gel7Item , 12 )
.AddResults( SIEXHS.lightItem , 2 )
.SetSelfIcon( "light" )

.NewRecipe( "wood" )
.SetEnergy( 1250 )
.SetEnabled( true )
.SetRecipeTypes( SIEXHS.recipeType )
.AddCosts( "wood" , 2000 )
.AddCosts( "stone" , 100 )
.AddCosts( SIEXHS.gel3Item , 25 )
.AddCosts( SIEXHS.coreItem )
.AddResults( "wood" , 2360 )
.AddResults( SIPackers.SingleItemProduct( SIEXHS.coreItem , 0.85 , 1 , 1 , 1 ) )
.SetSelfIcon( "wood" )