SIGen.NewSubGroup( "hyperspace-teleporter-base" )

SIEXHS.coreItem = SIGen.NewItem( "main-core" , 1 ).GetCurrentEntityName()
SIEXHS.wallItem = SIGen.NewItem( "super-wall" , 25 ).GetCurrentEntityName()
SIEXHS.gelItem = SIGen.NewItem( "gel" , 45 ).GetCurrentEntityName()

SIGen

.NewRecipe( SIEXHS.coreItem )
.SetEnergy( 10 )
.SetEnabled( true )
.AddCosts( "stone" , 10 )
.AddCosts( "iron-ore" , 1 )
.AddCosts( "copper-ore" , 1 )
.AddResults( SIPackers.SingleItemProduct( SIEXHS.coreItem , 0.002 , 1 , 1 , 1 ) )
.AddResults( SIPackers.SingleItemProduct( "stone" , 0.65 , 2 , 3 , 3 ) )
.SetSelfIcon( "main-core" )

.NewRecipe( SIEXHS.wallItem )
.SetEnergy( 25 )
.SetEnabled( true )
.AddCosts( "automation-science-pack" , 4 )
.AddCosts( "stone-wall" , 15 )
.AddCosts( "steel-plate" , 25 )
.AddCosts( SIEXHS.coreItem , 1 )
.AddResults( SIEXHS.wallItem , 2 )
.AddResults( SIPackers.SingleItemProduct( SIEXHS.coreItem , 1 , nil , nil , 1 ) )
.SetSelfIcon( "super-wall" )

.NewRecipe( SIEXHS.gelItem )
.SetEnergy( 16 )
.SetEnabled( true )
.SetRecipeTypes( "advanced-crafting" )
.AddCosts( "coal" , 32 )
.AddCosts( "copper-ore" , 25 )
.AddCosts( SIPackers.SingleFluidIngredient( "steam" , 200 , 150 , 220 ) )
.AddCosts( SIEXHS.coreItem , 1 )
.AddResults( SIEXHS.gelItem , 5 )
.AddResults( SIPackers.SingleItemProduct( SIEXHS.coreItem , 1 , nil , nil , 1 ) )
.SetSelfIcon( "gel" )